Add PR template in ivanov2103_microservices repository
Otus-DevOps-2018-02/ivanov2103_microservices pull request #1
Opened 2018-03-10 09:28 UTC by ivanov2103

homework-02b.
Template "PULL_REQUEST_TEMPLATE.md" filled.

2018-03-14 13:27 UTC, vitkhab requested changes
Оформи, пожалуйста, PR согласно шаблону и проставь label'ы `Homework-2` и `Git`

2018-03-15 13:51 UTC, ivanov2103 commented
Метку homework-02b-tag заменил на Homework-2, git - на Git. Прошу пояснить, в чем ошибка заполнения шаблона PR? Или нужен комментарий PR по шаблону? Однозначно в задаче не сказано об этом. Комментарий отредактировал.
Относительно же меток в задаче сказано следующее:
Должны быть проставлены правильные label'ы:
• С номером домашнего задания, например,
"homework-02a"
• С темой домашнего задания, например, "git"

2018-03-19 18:37 UTC, Nklya commented
Добавить labels означает кликнуть на шестеренку справа от надписи "Labels" и выбрать или создать указанные в ДЗ.
<img width="229" alt="screen shot 2018-03-19 at 21 36 37" src="https://user-images.githubusercontent.com/26086394/37615197-ba8063fc-2bbd-11e8-8264-7ddd4c11dfce.png">

2018-03-19 18:38 UTC, Nklya commented
Labels это не теги гита

2018-03-20 14:04 UTC, ivanov2103 commented
Спасибо, добавил.

2018-03-21 10:13 UTC, vitkhab approved these changes
Спасибо, что поправил. Все сделано классно! Можно мерджить

2018-03-22 15:25 UTC, merged